package com.ikoori.util;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {
	public String getStoreno() {
		return get("storeno");
	}

	public void setStoreno(String storeno) {
		set("storeno", storeno);
	}

	public String getTemplate() {
		return get("template");
	}

	public void setTemplate(String template) {
		set("template", template);
	}

	public String getParams() {
		return get("params");
	}

	public void setParams(String params) {
		set("params", params);
	}

}
